### ISSUE TITLE
NULL value found (oracle DB)

### ISSUE THREAD

**Issue by wKollendorf** [sfu-db/connector-x#333] opened 2022-08-24 14:16 UTC
#### What language are you using?

**Python**

#### What version are you using?

0.3.1a3

#### What database are you using?

Oracle

#### What dataframe are you using?

polars

#### Can you describe your bug?

When quering a table with a column containing null values and applying an math operation to it, an error is returned by cx.read_sql. When quering without calculation null is returned without any error (expected behaviour). So when doing some calculation with null values, the result also should be null, without throwing an error.

##### Database setup if the error only happens on specific data or data type

COLUMN_NAME DATA_TYPE          NULLABLE    DATA_DEFAULT
col1                     BINARY_FLOAT    yes                (null)
col1                     BINARY_FLOAT    yes                (null)

INSERT INTO test ("col1", "col2") VALUES (123, null)
INSERT INTO test ("col1", "col2") VALUES (456, null)

##### Example query / code

```
import connectorx as cx

query = 'select col1, round(col2*1000, 2) from test'

df = cx.read_sql( conn, query, return_type='polars') 
```

#### What is the error?

NULL value found

**Comment by wangxiaoying** [comment] 2022-08-31 18:12
Hi @wKollendorf , thanks for reporting this error. Can you try `pip install connectorx==0.3.1a4` to see whether the new version works?

**Comment by wKollendorf** [comment] 2022-09-01 08:58
Hi @wangxiaoying, thanks it is working now! By the way, pip only found version 0.3.1a1. I just built it from master (version 0.3.1.a5).

**Comment by wangxiaoying** [comment] 2022-09-01 18:26
> By the way, pip only found version 0.3.1a1. I just built it from master (version 0.3.1.a5).

I'm not sure whether it is caused by your dependency issue. But it seems working for me locally: 
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/5569610/187986128-e72bcd95-ec85-4ac7-b1a1-5c495a9d85b4.png"> Anyway I will close this issue. Thanks for the response!

**Closed by wangxiaoying** 2022-09-01 18:26 UTC
Labels: bug
