### ISSUE TITLE
Partition_on without partition_range gives a `RuntimeError`

### ISSUE THREAD

**Issue by braaannigan** [sfu-db/connector-x#407] opened 2022-11-22 16:22 UTC
#### What language are you using?

Python
#### What version are you using?

0.3.1
#### What database are you using?

SQLite
#### What dataframe are you using?

Polars
#### Can you describe your bug?

Without any partition arguments we can query the DB. With `partition_on` and `partition_num` arguments I get a RuntimeError

##### Example query / code
Create a small DB with Polars/Pandas and sqlite3
```python
import polars as pl
import sqlite3
import connectorx as cx

dfPandas = pl.DataFrame(
    {"A":[0,1,2],"B":[3,4,5]}).to_pandas()

sqliteDB = "data.sqlite"

sqliteConnection = sqlite3.connect(sqliteDB)
# Create the database
(
    dfPandas
    .to_sql('records', sqliteConnection, if_exists='replace', index=False)
)

DBConnection = 'sqlite://' + sqliteDB  
# This works if we comment out the partition_on and partition_num arguments
(
    cx.read_sql(
        conn = DBConnection,
        query = "select * from records",
        partition_on="A", 
        partition_num=2,
    )
)
```

#### What is the error?

```
RuntimeError                              Traceback (most recent call last)
Cell In [36], line 2
      1 (
----> 2     cx.read_sql(
      3         conn = polarsDBConnection,
      4         query = "select * from records",
      5         partition_on="A", 
      6         partition_num=2,
      7         # partition_range=(0,1)
      8 
      9     )
     10 )

File /usr/local/lib/python3.10/site-packages/connectorx/__init__.py:224, in read_sql(conn, query, return_type, protocol, partition_on, partition_range, partition_num, index_col)
    221 except ModuleNotFoundError:
    222     raise ValueError("You need to install pandas first")
--> 224 result = _read_sql(
    225     conn,
    226     "pandas",
    227     queries=queries,
    228     protocol=protocol,
    229     partition_query=partition_query,
    230 )
    231 df = reconstruct_pandas(result)
    233 if index_col is not None:

RuntimeError: no such table: records
```

Thanks for any help you can offer.

**Comment by wangxiaoying** [comment] 2022-11-24 02:43
Hi @braaannigan , the error suggesting that there is no table called `records`. Can you make sure your code of `to_sql` has been committed before invoking connectorx?

**Closed as completed** 2022-12-01 18:41 UTC
Labels: bug

**Comment by wangxiaoying** [comment] 2022-12-01 18:44
Hi @braaannigan , I see. Thanks for the given example, I can reproduce it from my side.

It looks like the error is due to the parsing on the file path when we issue the query to get the range of the partition column. I have fixed it in [this commit](https://github.com/sfu-db/connector-x/commit/1b767a84612bb877cdaa3fd9f84bf154bb1c011c). And will include it in our next release.

In the meanwhile, a simple workaround for this issue is to use the absolute path of the data file instead of a relative path. Like changing your `sqliteDB = "data.sqlite"` into `sqliteDB = "/User/xxx/data.sqlite"`.

Thanks for the report on this bug!

**Comment by braaannigan** [comment] 2022-12-02 12:43
> Hi @braaannigan , I see. Thanks for the given example, I can reproduce it from my side.
> 
> It looks like the error is due to the parsing on the file path when we issue the query to get the range of the partition column. I have fixed it in [this commit](https://github.com/sfu-db/connector-x/commit/1b767a84612bb877cdaa3fd9f84bf154bb1c011c). And will include it in our next release.
> 
> In the meanwhile, a simple workaround for this issue is to use the absolute path of the data file instead of a relative path. Like changing your `sqliteDB = "data.sqlite"` into `sqliteDB = "/User/xxx/data.sqlite"`.
> 
> Thanks for the report on this bug!

Thanks for the fix @wangxiaoying 😊
