### ISSUE TITLE
AssertionError of unknown source

### ISSUE THREAD

**Issue by jtlz2** [sfu-db/connector-x#236] opened 2022-02-15 07:17 UTC
Absolutely love connectorx and the speedup - thank you!

I'm getting the following `AssertionError` with a not very informative traceback. This exact call has worked fine in other circumstances. I will have to revert to pandas `read_sql` now :(

Any ideas?

Thanks again

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-e84a00ade808> in <module>
      3 query = "SELECT * FROM users"
      4 #users = pd.read_sql(query, conn)
----> 5 users = cx.read_sql(conn, query)

/opt/conda/lib/python3.7/site-packages/connectorx/__init__.py in read_sql(conn, query, return_type, protocol, partition_on, partition_range, partition_num, index_col)
    123             partition_query=partition_query,
    124         )
--> 125         df = reconstruct_pandas(result)
    126 
    127         if index_col is not None:

/opt/conda/lib/python3.7/site-packages/connectorx/__init__.py in reconstruct_pandas(df_infos)
    215                 pd.core.internals.make_block(
    216                     pd.core.arrays.BooleanArray(block_data[0], block_data[1]),
--> 217                     placement=binfo.cids[0],
    218                 )
    219             )

/opt/conda/lib/python3.7/site-packages/pandas/core/internals/blocks.py in make_block(values, placement, klass, ndim, dtype)
   3039         values = DatetimeArray._simple_new(values, dtype=dtype)
   3040 
-> 3041     return klass(values, ndim=ndim, placement=placement)
   3042 
   3043 

/opt/conda/lib/python3.7/site-packages/pandas/core/internals/blocks.py in __init__(self, values, placement, ndim)
   1725     def __init__(self, values, placement, ndim=None):
   1726         values = self._maybe_coerce_values(values)
-> 1727         super().__init__(values, placement, ndim)
   1728 
   1729     def _maybe_coerce_values(self, values):

/opt/conda/lib/python3.7/site-packages/pandas/core/internals/blocks.py in __init__(self, values, placement, ndim)
   1606         # its length
   1607         if not isinstance(placement, libinternals.BlockPlacement):
-> 1608             placement = libinternals.BlockPlacement(placement)
   1609 
   1610         # Maybe infer ndim from placement

pandas/_libs/internals.pyx in pandas._libs.internals.BlockPlacement.__init__()

AssertionError: 
```

**Comment by wangxiaoying** [comment] 2022-02-15 19:12
Hi @jtlz2 , could you provide more information about the query you issue so we can reproduce the error? Including:

* Which database are you using?
* What are the column types/schema of the query result?
* Would be better if we could have a simple query + sample data that could reproduce the error.

**Comment by wangxiaoying** [comment] 2022-03-13 07:56
I will close this issue since it looks the same with https://github.com/sfu-db/connector-x/discussions/244#discussioncomment-2321209 and can be solved by updating pandas to latest version. Please feel free to reopen it.

**Closed by wangxiaoying** 2022-03-13 07:56 UTC
