### ISSUE TITLE
Get Postgres EOF with TimescaleDB

### ISSUE THREAD

**Issue by icanwalkinyourmind** [sfu-db/connector-x#118] opened 2021-09-15 09:12 UTC
DB version: timescaledb:2.4.0-pg13
ConenctorX version: 0.2.0 
I'm trying to execute same query with time_bucket function and time_bucket_gapfill, in frist case it works fine.
But with time_bucket_gapfill i'm getting Postgres EOF error
Heare is query:
```sql
select time_bucket('1 minute', time) as "DateTime",
max(CASE WHEN signal_id = 4 THEN measurements.value END) as col
from measurements WHERE time >= {} AND  time <= {} group by "DateTime" order by "DateTime"
```
Also gapfill variant works fine when i execute query with sqlalchemy engine

**Comment by wangxiaoying** [comment] 2021-09-16 04:56
@icanwalkinyourmind Thanks for the report. However I cannot reproduce your error on timescaldb using function time_bucket_gapfill. Can you provide more information such as the table schema? Also does this error happens all the time no matter how you vary the predicates? If not, it would be better if some sample data that can trigger the error are also provided.

Also is your database updating? The EOF error means the number of rows in the returned result is smaller than what we expected (in the beginning we would first issue a count query to now the number of rows in order to preallocate the dataframe). So if the data is updating it might cause the issue.

**Comment by wangxiaoying** [comment] 2022-01-13 06:16
I will close this issue since it's not active. Feel free to reopen it.

**Closed by wangxiaoying** 2022-01-13 06:16 UTC
